services:
  db:
    image: postgres:15.0
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: blocklance-ceramic
      POSTGRES_PASSWORD: blocklance
      POSTGRES_DB: ceramic
  app:
    build: .
    ports:
      - "7007:7007"
    env_file:
      - .env
    environment:
      ADMIN_DID: ${ADMIN_DID}
      AWS_RDS_URL: ${AWS_RDS_URL}
    depends_on:
      - db
